export interface StatisticAiRowCatalogItem {
  row: number;
  section: string;
  label: string;
}

export const STATISTIC_AI_ROW_CATALOG: StatisticAiRowCatalogItem[] = [
  { row: 108, section: "5. RESULTADOS OPERATIVOS", label: "Cantidad de inspecciones a embarcaciones con acta" },
  { row: 109, section: "5. RESULTADOS OPERATIVOS", label: "Cantidad de inspecciones visuales a embarcaciones sin acta" },
  { row: 110, section: "5. RESULTADOS OPERATIVOS", label: "Cantidad de inspecciones a motocicletas" },
  { row: 111, section: "5. RESULTADOS OPERATIVOS", label: "Cantidad de inspecciones a vehiculos" },
  { row: 112, section: "5. RESULTADOS OPERATIVOS", label: "Embarcaciones con documentos al dia" },
  { row: 113, section: "5. RESULTADOS OPERATIVOS", label: "Embarcaciones sin documentos" },
  { row: 114, section: "5. RESULTADOS OPERATIVOS", label: "Sin titulo de propiedad o matricula" },
  { row: 115, section: "5. RESULTADOS OPERATIVOS", label: "Sin certificado de navegabilidad" },
  { row: 116, section: "5. RESULTADOS OPERATIVOS", label: "Sin licencia de actividad" },
  { row: 117, section: "5. RESULTADOS OPERATIVOS", label: "Sin zarpe cuando corresponde" },
  { row: 118, section: "5. RESULTADOS OPERATIVOS", label: "Sin certificado de zafarrancho embarcacion" },
  { row: 119, section: "5. RESULTADOS OPERATIVOS", label: "Embarcaciones con documentos vencidos" },
  { row: 120, section: "5. RESULTADOS OPERATIVOS", label: "Titulo de propiedad o matricula vencido" },
  { row: 121, section: "5. RESULTADOS OPERATIVOS", label: "Certificado de navegabilidad vencido" },
  { row: 122, section: "5. RESULTADOS OPERATIVOS", label: "Licencia de actividad vencida" },
  { row: 123, section: "5. RESULTADOS OPERATIVOS", label: "Zarpe vencido" },
  { row: 124, section: "5. RESULTADOS OPERATIVOS", label: "Certificado zafarrancho embarcacion vencido" },
  { row: 125, section: "5. RESULTADOS OPERATIVOS", label: "Canon de licencia de pesca vencido" },
  { row: 126, section: "5. RESULTADOS OPERATIVOS", label: "Embarcaciones sin dispositivos de seguridad" },
  { row: 127, section: "5. RESULTADOS OPERATIVOS", label: "Embarcaciones que exceden autonomia" },
  { row: 128, section: "5. RESULTADOS OPERATIVOS", label: "Embarcaciones con actividades diferentes a las autorizadas" },
  { row: 129, section: "5. RESULTADOS OPERATIVOS", label: "Embarcaciones con exceso de combustible" },
  { row: 130, section: "5. RESULTADOS OPERATIVOS", label: "Embarcaciones con exceso de personas" },
  { row: 131, section: "5. RESULTADOS OPERATIVOS", label: "Embarcaciones con AIS" },
  { row: 132, section: "5. RESULTADOS OPERATIVOS", label: "Embarcaciones sin AIS" },
  { row: 133, section: "5. RESULTADOS OPERATIVOS", label: "Embarcaciones con inconsistencias en zarpe" },
  { row: 134, section: "5. RESULTADOS OPERATIVOS", label: "Embarcaciones asistidas" },
  { row: 135, section: "5. RESULTADOS OPERATIVOS", label: "Embarcaciones rescatadas" },
  { row: 136, section: "5. RESULTADOS OPERATIVOS", label: "Embarcaciones con control del DET realizado" },
  { row: 137, section: "5. RESULTADOS OPERATIVOS", label: "Cumplen disposiciones del DET" },
  { row: 138, section: "5. RESULTADOS OPERATIVOS", label: "No cumplen disposiciones del DET" },
  { row: 139, section: "5. RESULTADOS OPERATIVOS", label: "Personas con documentos al dia" },
  { row: 140, section: "5. RESULTADOS OPERATIVOS", label: "Personas sin documentos" },
  { row: 141, section: "5. RESULTADOS OPERATIVOS", label: "Sin carnet de pesca" },
  { row: 142, section: "5. RESULTADOS OPERATIVOS", label: "Sin certificado zafarrancho capitan" },
  { row: 143, section: "5. RESULTADOS OPERATIVOS", label: "Cantidad de tripulacion sin zafarrancho" },
  { row: 144, section: "5. RESULTADOS OPERATIVOS", label: "Personas retenidas para investigacion en AP" },
  { row: 145, section: "5. RESULTADOS OPERATIVOS", label: "Personas aprehendidas" },
  { row: 146, section: "5. RESULTADOS OPERATIVOS", label: "Personas detenidas" },
  { row: 148, section: "5. RESULTADOS OPERATIVOS", label: "Personas indocumentadas colombianas" },
  { row: 149, section: "5. RESULTADOS OPERATIVOS", label: "Personas indocumentadas nicaraguenses" },
  { row: 150, section: "5. RESULTADOS OPERATIVOS", label: "Personas indocumentadas salvadorenas" },
  { row: 151, section: "5. RESULTADOS OPERATIVOS", label: "Personas indocumentadas ecuatorianas" },
  { row: 152, section: "5. RESULTADOS OPERATIVOS", label: "Personas indocumentadas mexicanas" },
  { row: 153, section: "5. RESULTADOS OPERATIVOS", label: "Personas indocumentadas jamaiquinas" },
  { row: 154, section: "5. RESULTADOS OPERATIVOS", label: "Personas indocumentadas panamenas" },
  { row: 155, section: "5. RESULTADOS OPERATIVOS", label: "Personas indocumentadas otras" },
  { row: 156, section: "5. RESULTADOS OPERATIVOS", label: "Personas desaparecidas" },
  { row: 157, section: "5. RESULTADOS OPERATIVOS", label: "Personas rescatadas" },
  { row: 158, section: "5. RESULTADOS OPERATIVOS", label: "Personas fallecidas recuperadas" },
  { row: 159, section: "5. RESULTADOS OPERATIVOS", label: "Personas enfermas o heridas trasladadas" },
  { row: 160, section: "5. RESULTADOS OPERATIVOS", label: "Personas desalojadas de areas protegidas" },
  { row: 161, section: "5. RESULTADOS OPERATIVOS", label: "Rescate de flora silvestre" },
  { row: 162, section: "5. RESULTADOS OPERATIVOS", label: "Rescate de fauna silvestre" },
  { row: 163, section: "5. RESULTADOS OPERATIVOS", label: "Vehiculos desalojados de playas" },
  { row: 164, section: "5. RESULTADOS OPERATIVOS", label: "Cantidad de bienes sustraidos" },
  { row: 166, section: "6. DECOMISOS", label: "Armas de fuego" },
  { row: 167, section: "6. DECOMISOS", label: "Municiones" },
  { row: 168, section: "6. DECOMISOS", label: "Arma blanca" },
  { row: 169, section: "6. DECOMISOS", label: "Artes de pesca" },
  { row: 170, section: "6. DECOMISOS", label: "Cocaina kg" },
  { row: 171, section: "6. DECOMISOS", label: "Cocaina puntas" },
  { row: 173, section: "6. DECOMISOS", label: "Marihuana kilos" },
  { row: 174, section: "6. DECOMISOS", label: "Marihuana puchos" },
  { row: 175, section: "6. DECOMISOS", label: "Marihuana matas" },
  { row: 176, section: "6. DECOMISOS", label: "Marihuana cigarros" },
  { row: 177, section: "6. DECOMISOS", label: "Piedras de crack" },
  { row: 178, section: "6. DECOMISOS", label: "Heroina kg" },
  { row: 179, section: "6. DECOMISOS", label: "Extasis unidades" },
  { row: 180, section: "6. DECOMISOS", label: "Gasolina litros" },
  { row: 181, section: "6. DECOMISOS", label: "Diesel litros" },
  { row: 182, section: "6. DECOMISOS", label: "Aceite cuartos" },
  { row: 183, section: "6. DECOMISOS", label: "Motosierras" },
  { row: 184, section: "6. DECOMISOS", label: "Huevos de tortuga" },
  { row: 185, section: "6. DECOMISOS", label: "Carne de tortuga kg" },
  { row: 186, section: "6. DECOMISOS", label: "Productos pesqueros kg" },
  { row: 187, section: "6. DECOMISOS", label: "Fauna silvestre" },
  { row: 188, section: "6. DECOMISOS", label: "Subproductos de fauna silvestre" },
  { row: 189, section: "6. DECOMISOS", label: "Flora silvestre" },
  { row: 190, section: "6. DECOMISOS", label: "Madera pulgadas cubicas" },
  { row: 191, section: "6. DECOMISOS", label: "Embarcaciones por Ley de Pesca" },
  { row: 192, section: "6. DECOMISOS", label: "Embarcaciones por narcotrafico" },
  { row: 193, section: "6. DECOMISOS", label: "Embarcaciones por ley de combustible" },
  { row: 194, section: "6. DECOMISOS", label: "Embarcaciones con inconsistencias registrales" },
  { row: 195, section: "6. DECOMISOS", label: "Jet Ski con inconsistencias registrales" },
  { row: 196, section: "6. DECOMISOS", label: "Embarcaciones por Ley de Vida Silvestre" },
  { row: 197, section: "6. DECOMISOS", label: "Embarcaciones por Ley Forestal" },
  { row: 198, section: "6. DECOMISOS", label: "Motores por Ley de Pesca" },
  { row: 199, section: "6. DECOMISOS", label: "Motores por narcotrafico" },
  { row: 200, section: "6. DECOMISOS", label: "Automoviles" },
  { row: 201, section: "6. DECOMISOS", label: "Motocicletas" },
  { row: 202, section: "6. DECOMISOS", label: "Bicicletas" },
  { row: 204, section: "7. HALLAZGOS", label: "Armas de fuego" },
  { row: 205, section: "7. HALLAZGOS", label: "Municiones" },
  { row: 206, section: "7. HALLAZGOS", label: "Arma blanca" },
  { row: 207, section: "7. HALLAZGOS", label: "Artes de pesca" },
  { row: 208, section: "7. HALLAZGOS", label: "Cocaina kg" },
  { row: 209, section: "7. HALLAZGOS", label: "Cocaina punta" },
  { row: 211, section: "7. HALLAZGOS", label: "Marihuana kilos" },
  { row: 212, section: "7. HALLAZGOS", label: "Marihuana puchos" },
  { row: 213, section: "7. HALLAZGOS", label: "Marihuana matas" },
  { row: 214, section: "7. HALLAZGOS", label: "Marihuana cigarros" },
  { row: 215, section: "7. HALLAZGOS", label: "Piedras de crack" },
  { row: 216, section: "7. HALLAZGOS", label: "Heroina kg" },
  { row: 217, section: "7. HALLAZGOS", label: "Extasis unidades" },
  { row: 218, section: "7. HALLAZGOS", label: "Gasolina litros" },
  { row: 219, section: "7. HALLAZGOS", label: "Diesel litros" },
  { row: 220, section: "7. HALLAZGOS", label: "Aceite cuartos" },
  { row: 221, section: "7. HALLAZGOS", label: "Motosierras" },
  { row: 222, section: "7. HALLAZGOS", label: "Huevos de tortuga" },
  { row: 223, section: "7. HALLAZGOS", label: "Carne de tortuga kg" },
  { row: 224, section: "7. HALLAZGOS", label: "Productos pesqueros kg" },
  { row: 225, section: "7. HALLAZGOS", label: "Fauna silvestre" },
  { row: 226, section: "7. HALLAZGOS", label: "Subproductos de fauna silvestre" },
  { row: 227, section: "7. HALLAZGOS", label: "Flora silvestre" },
  { row: 228, section: "7. HALLAZGOS", label: "Madera pulgadas cubicas" },
  { row: 229, section: "7. HALLAZGOS", label: "Embarcaciones por Ley de Pesca" },
  { row: 230, section: "7. HALLAZGOS", label: "Embarcaciones por narcotrafico" },
  { row: 231, section: "7. HALLAZGOS", label: "Embarcaciones por ley de combustible" },
  { row: 232, section: "7. HALLAZGOS", label: "Embarcaciones con inconsistencias registrales" },
  { row: 233, section: "7. HALLAZGOS", label: "Jet Ski con inconsistencias registrales" },
  { row: 234, section: "7. HALLAZGOS", label: "Embarcaciones por Ley de Vida Silvestre" },
  { row: 235, section: "7. HALLAZGOS", label: "Embarcaciones por Ley Forestal" },
  { row: 236, section: "7. HALLAZGOS", label: "Motores por Ley de Pesca" },
  { row: 237, section: "7. HALLAZGOS", label: "Motores por narcotrafico" },
  { row: 238, section: "7. HALLAZGOS", label: "Automoviles" },
  { row: 239, section: "7. HALLAZGOS", label: "Motocicletas" },
  { row: 240, section: "7. HALLAZGOS", label: "Bicicletas" },
  { row: 242, section: "8. DENUNCIAS", label: "Denuncias recibidas por sistema 911" },
  { row: 243, section: "8. DENUNCIAS", label: "Denuncias recibidas por otros medios" },
  { row: 244, section: "8. DENUNCIAS", label: "Denuncias atendidas" },
  { row: 245, section: "8. DENUNCIAS", label: "Falsas alarmas" },
  { row: 247, section: "8. DENUNCIAS", label: "Presentadas al Ministerio Publico" },
  { row: 248, section: "8. DENUNCIAS", label: "Presentadas a INCOPESCA" },
  { row: 249, section: "8. DENUNCIAS", label: "Presentadas a MINAE" },
  { row: 250, section: "8. DENUNCIAS", label: "Presentadas a Capitania de Puerto" },
  { row: 251, section: "8. DENUNCIAS", label: "Presentadas a Municipalidad" },
  { row: 252, section: "8. DENUNCIAS", label: "Presentadas a Tribunal Ambiental" },
  { row: 253, section: "8. DENUNCIAS", label: "Presentadas a Ministerio de Salud" },
  { row: 254, section: "8. DENUNCIAS", label: "Presentadas a SENASA" },
  { row: 255, section: "8. DENUNCIAS", label: "Presentadas a Migracion" },
  { row: 256, section: "8. DENUNCIAS", label: "Presentadas a Tribunal contravencional" },
  { row: 257, section: "8. DENUNCIAS", label: "Presentadas a otro" },
  { row: 259, section: "9. SERVICIOS", label: "Obras comunales" },
  { row: 260, section: "9. SERVICIOS", label: "Charlas en centros de ensenanza" },
  { row: 261, section: "9. SERVICIOS", label: "Charlas en comunidades" },
  { row: 262, section: "9. SERVICIOS", label: "Limpieza de playas" },
  { row: 263, section: "9. SERVICIOS", label: "Notificaciones" },
  { row: 264, section: "9. SERVICIOS", label: "Traslado de testigos" },
  { row: 265, section: "9. SERVICIOS", label: "Traslado de detenidos" },
  { row: 266, section: "9. SERVICIOS", label: "Valoraciones economicas del dano ambiental" },
  { row: 267, section: "9. SERVICIOS", label: "Certificaciones a la Fiscalia" },
  { row: 268, section: "9. SERVICIOS", label: "Traslado de comitivas" },
  { row: 269, section: "9. SERVICIOS", label: "Custodia de embarcacion" },
  { row: 270, section: "9. SERVICIOS", label: "Custodia de vehiculo" },
  { row: 272, section: "10. OTRAS ACTIVIDADES", label: "Reuniones de coordinacion" },
  { row: 273, section: "10. OTRAS ACTIVIDADES", label: "Talleres y seminarios" },
  { row: 274, section: "10. OTRAS ACTIVIDADES", label: "Consultas al Departamento Legal del Guardacostas" },
  { row: 275, section: "10. OTRAS ACTIVIDADES", label: "Asistencias a capacitacion" },
  { row: 276, section: "10. OTRAS ACTIVIDADES", label: "Actividades de extension a comunidades" },
  { row: 277, section: "10. OTRAS ACTIVIDADES", label: "Colaboracion con practicas de la Academia del Guardacostas" },
];

export const STATISTIC_AI_ROW_NUMBERS = STATISTIC_AI_ROW_CATALOG.map((item) => item.row);
export const STATISTIC_AI_ROW_SET = new Set(STATISTIC_AI_ROW_NUMBERS);

export const isStatisticAiRowAllowed = (row: number) => STATISTIC_AI_ROW_SET.has(row);
